version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: kanban_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: kanban
      POSTGRES_PASSWORD: kanban
      POSTGRES_DB: kanban
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: